// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs0c1-b1K-ooE6loN6kx9yfh16IR0W_EU',
    appId: '1:413117789548:android:dce828aee26cb668c16f49',
    messagingSenderId: '413117789548',
    projectId: 'srikandi-sehat-app',
    storageBucket: 'srikandi-sehat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY98kLo0UpYWPzIj14MutEKxoMmwoXOn8',
    appId: '1:413117789548:ios:96cd92969f8f07abc16f49',
    messagingSenderId: '413117789548',
    projectId: 'srikandi-sehat-app',
    storageBucket: 'srikandi-sehat-app.firebasestorage.app',
    iosBundleId: 'com.example.srikandiSehatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8RCsbQy9dqcwsVKG4k8NPWiR8NHk_mY',
    appId: '1:413117789548:web:4168999aea2f0bb2c16f49',
    messagingSenderId: '413117789548',
    projectId: 'srikandi-sehat-app',
    authDomain: 'srikandi-sehat-app.firebaseapp.com',
    storageBucket: 'srikandi-sehat-app.firebasestorage.app',
    measurementId: 'G-J8TWBH2P10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY98kLo0UpYWPzIj14MutEKxoMmwoXOn8',
    appId: '1:413117789548:ios:96cd92969f8f07abc16f49',
    messagingSenderId: '413117789548',
    projectId: 'srikandi-sehat-app',
    storageBucket: 'srikandi-sehat-app.firebasestorage.app',
    iosBundleId: 'com.example.srikandiSehatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs8RCsbQy9dqcwsVKG4k8NPWiR8NHk_mY',
    appId: '1:413117789548:web:f77ca293d34a203bc16f49',
    messagingSenderId: '413117789548',
    projectId: 'srikandi-sehat-app',
    authDomain: 'srikandi-sehat-app.firebaseapp.com',
    storageBucket: 'srikandi-sehat-app.firebasestorage.app',
    measurementId: 'G-BEBTJZVR84',
  );

}